# This is a simple configuration for our Nginx server

server {
  # Listen on port 80 for incoming connections
  listen 80;

  # Set the root directory where our static files are located
  root /usr/share/nginx/html;

  # This tells Nginx to look for an index.html file for root requests
  index index.html;

  # This is the most important part for a Single Page Application (SPA) like React.
  # If a user requests a path like '/dashboard', Nginx will first look for a file or directory
  # with that name. If it doesn't find one, it will fall back to serving the /index.html file.
  # This allows React Router to take over and handle the client-side routing.
  location / {
    try_files $uri $uri/ /index.html;
  }
}
