spring.application.name=csat
server.port=8080
spring.datasource.url=jdbc:postgresql://localhost:5432/csat_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
jwt.secret=bVp2eERoR2tYcDJ6JTVFcStYcyVlRG1KJVleJnAnRSpHcU1tUadfasdfjalksdjfkajsdkfadsjfajsdkfjadsjfkasjdfkjdsafkasdfsadjfkdDE=
jwt.expiration=900000
#spring.security.user.password=test
#jwt.secret=8AfQr6K+uoBVjWha73y9pUDnuo3QCvJsM3KIhaTVE6Q=
